config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :comments
  resources :events do
    resources :matches
  end

  root 'events#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :text
#  day        :integer
#  month      :integer
#  year       :integer
#  level      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ActiveRecord::Base

	has_many :matches, dependent: :destroy
	has_many :participations, dependent: :destroy
	has_many :teams, through: :participations

	validates :day, presence:true
	validates :month, presence:true
	validates :year, presence:true, :numericality => {:greater_than => 0}
	validates :name, presence:true, uniqueness:true
	validates :level, presence:true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource
	include TeamsHelper
	include MatchesHelper
	include EventsHelper

	def index
		@events = Event.all.where("id>?", 12).order(:name)
	end

	def new
		@event = Event.new
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to @event, notice:'Event successfully created'
		else
			render 'new'
		end
	end

	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
			redirect_to @event, notice:'Event successfully updated'
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy unless @event.nil?
		redirect_to events_path
	end	

	private

		def event_params
			params[:event].permit(:name, :day, :month, :year, :level)
		end

end

app/helpers/events_helper.rb
module EventsHelper
	require 'matrix'

	def show_date(event)
		"#{event.month}/#{event.day}/#{event.year}"
	end

	def show_level(event)
		content_tag(:span, event.level, class: "label label-warning label-as-badge")
	end

	def QP(event)
		teams = event.teams

		map = {}
		for i in 0..teams.size-1
			map[teams[i].number] = i
		end

		arr = Array.new(teams.size) {Array.new(3) {0}}		
		event.matches.includes(:red1, :red2, :blue1, :blue2).each do |m|
			r1 = map[m.red1.number]
			r2 = map[m.red2.number]
			b1 = map[m.blue1.number]
			b2 = map[m.blue2.number]

			arr[r1][0] += 1
			arr[r2][0] += 1
			arr[b1][0] += 1
			arr[b2][0] += 1

			if m.red_score > 0
				arr[r1][2] += 1
				arr[r2][2] += 1
			end
			if m.blue_score > 0
				arr[b1][2] += 1
				arr[b2][2] += 1
			end

			n = winningAlliance(m)
			if n == -1
				arr[r1][1] += 2
				arr[r2][1] += 2
			elsif n == 1
				arr[b1][1] += 2
				arr[b2][1] += 2
			elsif isPlayed(m)
				arr[r1][1] += 1
				arr[r2][1] += 1
				arr[b1][1] += 1
				arr[b2][1] += 1	
			end
		end

		hash = {}
		map.each do |k,v|
			hash[k] = arr[v]
		end
		hash
	end


	def OPR(event)
		teams = event.teams

		map = {}
		for i in 0..teams.size-1
			map[teams[i].number] = i
		end

		arr = Array.new(teams.size) {Array.new(teams.size) {0}}		
		b = Array.new(teams.size) {0}

		event.matches.includes(:red1, :red2, :blue1, :blue2).where('blue_score!=0 AND red_score!=0').each do |m|
			r1 = map[m.red1.number]
			r2 = map[m.red2.number]
			b1 = map[m.blue1.number]
			b2 = map[m.blue2.number]

			arr[r1][r1] += 1
			arr[r2][r2] += 1
			arr[b1][b1] += 1
			arr[b2][b2] += 1

			arr[r1][r2] += 1
			arr[r2][r1] += 1
			arr[b1][b2] += 1
			arr[b2][b1] += 1

			b[r1] += m.red_score
			b[r2] += m.red_score
			b[b1] += m.blue_score
			b[b2] += m.blue_score

		end


		mat = Matrix[*arr]
		solve = mat.lup.solve(b) rescue Array.new(teams.size){0}

		opr = {}
		map.each do |k,v|
			opr[k] = solve[v].to_f
		end

		opr
	end

end

app/views/events/_event.html.erb
<a href="<%= event_path(event) %>" class="thumbnail text-center" style="text-decoration:none; color:#2c3e50;">
<h2><%= event.name %></h2>
<h4><%= show_date(event) %></h4>
<h4><%= show_level(event) %></h4>
</a>

app/views/events/_form.html.erb
<div class="row col-md-10 col-md-ofset-1">

	<h1><%= controller.action_name.capitalize %> Event </h1>
	<br>
	<%= simple_form_for(@event, html:{class:'form-horizontal'}, wrapper: :horizontal_form) do |f| %>

		<% f.error_notification %>
		<%= f.input :name %>
		<%= f.input :month, collection: MONTHS  %>
		<%= f.input :day, collection: 1..31 %>
		<%= f.input :year %>
		<%= f.input :level, collection: LEVELS %>


		
		<div class="row text-right" %>
			<%= f.submit nil, class:'btn btn-primary'%>
			<%= link_to 'Cancel', :back, class:'btn btn-default' %>
		</div>
	<% end %>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>Florida FTC 2015-16 Events</h1>
</div>

<div class="text-right">
	<%= link_to 'New Event', new_event_path, class:'btn btn-primary text-right' if can? :modify, Event%>
</div>
<br>
<% @events.sort_by{|e| [-e.year, -e.month, -e.day] }.each_slice(3) do |events| %>
	<div class="row">
		<% events.each do |e| %>
			<div class="col-md-4">
				<%= render e %>
			</div>
		<% end %>
	</div>
<% end %>
<br>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<div class="page-header">
	<h1><%= @event.name %></h1>
  <h3><%= show_date(@event) %> &nbsp; <%= show_level(@event) %></h3>
</div>
<br>

<% participations = @event.participations.includes(:team)%>

<h2>Competing Teams</h2>
<% if current_user && (current_user.is?(:neutrinos) || current_user.is?(:admin)) %>
<table id="teams_table1" class="display">
  <thead>
    <tr>
      <th>Team #</th>
      <th>Name</th>
      <th>High Score</th>
      <th>Avg Score</th>
      <th>St Dev</th>
      <th>Avg Cont</th>
      <th>OPR</th>
      <th># Matches</th>
      <th>QP</th>
      <th>Win %</th>
    </tr>
  </thead>

  <tbody>
    <% participations.each do |p| %>
      <% t = p.team %>
      <tr>
        <td><%= t.number %></td>
        <td> <a href="<%= team_path(t) %>" style=" text-decoration: none;"> <%= t.name %></a></td>
        <td><%= p.high_score %></td>
        <td><%= p.avg_score %></td>
        <td><%= p.st_dev %></td>
        <td><%= p.avg_cont %></td>
        <td><%= p.opr.round(1) %></td>
        <td><%= "#{p.curMatches}/#{p.numMatches}" %></td>
        <td><%= p.qp %></td>
        <td><%= p.win_perc %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<table id="teams_table2" class="display">
  <thead>
    <tr>
      <th>Team #</th>
      <th>Name</th>
      <th>High Score</th>
      <th># Matches</th>
      <th>QP</th>
      <th>Win %</th>
    </tr>
  </thead>
  <tbody>
    <% participations.each do |p| %>
      <% t = p.team %>
      <tr>
        <td><%= t.number %></td>
        <td> <a href="<%= team_path(t) %>" style=" text-decoration: none;"> <%= t.name %></a></td>
        <td><%= p.high_score %></td>
        <td><%= "#{p.curMatches}/#{p.numMatches}" %></td>
        <td><%= p.qp %></td>
        <td><%= p.win_perc %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<script>
$(document).ready(
  function() {
    $('#teams_table1').DataTable({
        "order": [[ 6, "desc" ]],
        "paging": false,
         "scrollY":"600px",
         "scrollCollapse": true
    })
  }
  )
</script>

<script>
$(document).ready(
  function() {
    $('#teams_table2').DataTable({
        "order": [[ 4, "desc" ]],
        "paging": false,
         "scrollY":"600px",
         "scrollCollapse": true
    })
  }
  )
</script>

<% opr = Hash[participations.map {|p| [p.team_id, p.opr]}] %>

<br><br><br>
<% if can? :create, Match%>
<div class="text-right">
  <%= link_to 'New Match', new_event_match_path(@event), class:'btn btn-primary' %> 
</div>
<% end %>
<h2>Matches</h2>
<table id="matches_table" class = "display">
  <thead>
  <tr>
    <th>Match #</th>
    <th><%= red("Red 1") %></th>
    <th><%= red("Red 2") %></th>
    <th><%= blue("Blue 1") %></th>
    <th><%= blue("Blue 2") %></th>
    <th><%= red("Red") %></th>
    <th><%= blue("Blue") %></th>
    <% if current_user && (current_user.is?(:neutrinos) || current_user.is?(:admin)) %>
      <th>OPR Predicts</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% @event.matches.includes(:red1, :red2, :blue1, :blue2).order(number: :asc).each do |m| %>
      <tr>
      <% if can? :modify, Match %>
        <td> <a href="<%= event_match_path(m.event, m) %>"> <%= m.number %> </a></td>
      <% else  %>
        <td> <a href="<%= event_match_path(m.event, m) %>" style="color:#000000;  text-decoration: none;"> <%= m.number %> </a></td>
      <% end %>
        <td> <a href="<%= team_path(m.red1) %>" style="color:#FF0000; text-decoration: none;"> <%= m.red1.show_team %> </a></td>
        <td> <a href="<%= team_path(m.red2) %>" style="color:#FF0000; text-decoration: none;"> <%= m.red2.show_team %> </a></td>
        <td> <a href="<%= team_path(m.blue1) %>" style="color:#0000FF;  text-decoration: none;"> <%= m.blue1.show_team %> </a></td>
        <td> <a href="<%= team_path(m.blue2) %>" style="color:#0000FF;  text-decoration: none;"> <%= m.blue2.show_team %> </a></td>
        <td> <font color="RED"> <%= m.red_score == 0 ? '---' : m.red_score %> </font></td>
        <td> <font color="BLUE"><%= m.blue_score == 0 ? '---' : m.blue_score %> </font></td>

      <% if current_user && (current_user.is?(:neutrinos) || current_user.is?(:admin)) %>
        <% if !isPlayed(m) %>
          <% red = (opr[m.red1_id] + opr[m.red2_id]).round(0) %>
          <% blue = (opr[m.blue1_id] + opr[m.blue2_id]).round(0) %>

          <% if red>blue %>
            <td><font color="RED"><%= "RED #{red}-#{blue}" %></font></td>
          <% elsif blue>red %>
            <td><font color="BLUE"><%= "BLUE #{red}-#{blue}" %></font></td>
          <% else %>
            <td><%= "TIE #{red}-#{blue}" %></td>
          <% end %>
        <% else %>
          <td><%= "-----------" %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$(document).ready(
  function() {
    $('#matches_table').DataTable({
        "ordering": false,
        "paging": false,
         "scrollY":"600px",
         "scrollCollapse": true
    })
  }
  )
</script>

<br>
<br>
<div class="row text-right">
	<%= link_to fa_icon('pencil', text:'Edit Event'), edit_event_path(@event), class:'btn btn-default' if can? :modify, Event%> 
	<%= link_to fa_icon('trash-o', text:'Destroy Event'), @event, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' if can? :destroy, Event%>
</div>