config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :comments
  resources :events do
    resources :matches
  end

  root 'events#index'

end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id         :integer          not null, primary key
#  number     :integer
#  blue1_id   :integer
#  blue2_id   :integer
#  red1_id    :integer
#  red2_id    :integer
#  red_score  :integer
#  blue_score :integer
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Match < ActiveRecord::Base

	belongs_to :blue1, :class_name => "Team"
	belongs_to :blue2, :class_name => "Team"
	belongs_to :red1, :class_name => "Team"
	belongs_to :red2, :class_name => "Team"
	belongs_to :event
	has_many :comments, as: :commentable, dependent: :destroy

	validates :blue1_id, presence:true
	validates :blue2_id, presence:true
	validates :red1_id, presence:true
	validates :red2_id, presence:true
	validates :number, presence:true
	validates :red_score, presence:true, :numericality => {:greater_than_or_equal_to => 0}
	validates :blue_score, presence:true, :numericality => {:greater_than_or_equal_to => 0}
	validates :event_id, presence:true
	validate :validTeams
	validate :uniqueEventNum

	def validTeams
		if blue1_id == blue2_id
			errors.add(:blue1_id, "Repeated team")
			errors.add(:blue2_id, "Repeated team")
		elsif blue1_id == red1_id
			errors.add(:blue1_id, "Repeated team")
			errors.add(:red1_id, "Repeated team")
		elsif blue1_id == red2_id
			errors.add(:blue1_id, "Repeated team")
			errors.add(:red2_id, "Repeated team")
		elsif blue2_id == red1_id
			errors.add(:blue2_id, "Repeated team")
			errors.add(:red1_id, "Repeated team")
		elsif blue2_id == red2_id
			errors.add(:blue2_id, "Repeated team")
			errors.add(:red2_id, "Repeated team")
		elsif red1_id == red2_id
			errors.add(:red1_id, "Repeated team")
			errors.add(:red2_id, "Repeated team")
		end
	end

	def uniqueEventNum
		if Event.find(event_id).matches.where(number:number).size > 0
			errors.add(:number, "Number has already been taken") if Event.find(event_id).matches.where(number:number).first.id != id
		end
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	include TeamsHelper
	include MatchesHelper
	include EventsHelper

	before_action :set_event
	before_action :authenticate_user!, except: [:show]
	load_and_authorize_resource


	def new
		@match = Match.new(event_id: @event.id, blue_score: 0, red_score: 0)
	end

	def show
		@match = Match.find(params[:id])
	end

	def edit
		@match = Match.find(params[:id])
	end

	def create
		@match = Match.new(match_params)
		if @match.save
			addToEvent(@match)
			updateEvent(@event)
			redirect_to @event, notice:'Match successfully created'
		else
			render 'new'
		end
	end

	def update
		@match = Match.find(params[:id])
		if @match.update(match_params)
			addToEvent(@match)
			updateEvent(@event)
			redirect_to @event, notice:'Match successfully updated'
		else
			render 'edit'
		end
	end

	def destroy
		@match = Match.find(params[:id])
		@match.destroy unless @match.nil?
		updateEvent(@event)
		redirect_to @event
	end	

	private

		def match_params
			params[:match].permit(:number, :event_id, :blue1_id, :blue2_id, :red1_id, :red2_id, :blue_score, :red_score)
		end

		def set_event
			@event = Event.find(params[:event_id])
		end


end

app/helpers/matches_helper.rb
module MatchesHelper

	def getMatches(team)
		Match.where('event_id>? AND (blue1_id=? OR blue2_id=? OR red1_id=? OR red2_id=?)', 12, "#{team.id}", "#{team.id}", "#{team.id}", "#{team.id}")
	end
	
	def getEventMatches(team, event)
		Match.where('event_id = ? AND (blue1_id=? OR blue2_id=? OR red1_id=? OR red2_id=?)', "#{event.id}", "#{team.id}", "#{team.id}", "#{team.id}", "#{team.id}")
	end

	def getPlayedMatches(team)
		Match.where('event_id>? AND (blue_score!=0 AND red_score!=0 AND (blue1_id=? OR blue2_id=? OR red1_id=? OR red2_id=?))', 12, "#{team.id}", "#{team.id}", "#{team.id}", "#{team.id}")
	end

	def getPlayedEventMatches(team, event)
		Match.where('event_id = ? AND blue_score!=0 AND red_score!=0 AND (blue1_id=? OR blue2_id=? OR red1_id=? OR red2_id=?)', "#{event.id}", "#{team.id}", "#{team.id}", "#{team.id}", "#{team.id}")
	end


	def removeTeams(event)
		matches = event.matches
		event.participations.each do |p|
			if matches.where('blue1_id=? OR blue2_id=? OR red1_id=? OR red2_id=?', "#{p.team.id}", "#{p.team.id}", "#{p.team.id}", "#{p.team.id}").size == 0
				team = p.team
				p.destroy
				updateTeam(team)
			end
		end
	end
	

	def updateEvent(event)
		removeTeams(event)
		qp = QP(event)
		op = OPR(event)
		event.participations.each do |p|			
			if !p.destroyed?
				updateParticipation(p)
				p.numMatches = qp[p.team.number][0]
				p.curMatches = qp[p.team.number][2]
				p.qp = qp[p.team.number][1]
				p.opr = op[p.team.number]
				p.save
			end
		end
	end

	def addToEvent(match)
		event = match.event
		teams = getTeams(match)
		teams.each do |t|
			if !event.teams.include?(t)
				p = Participation.create(event_id: event.id, team_id: t.id)
				p.save
			end
		end
	end

	def isPlayed(match)
		match.red_score != 0 && match.blue_score != 0
	end

	def predict(match)
		if !isPlayed(match)
			or1 = match.red1.participations.where(event_id: match.event.id).first.opr
			or2 = match.red2.participations.where(event_id: match.event.id).first.opr
			ob1 = match.blue1.participations.where(event_id: match.event.id).first.opr
			ob2 = match.blue2.participations.where(event_id: match.event.id).first.opr

			red = (or1 + or2).round(0)
			blue = (ob1 + ob2).round(0)

			if red>blue
				"RED #{red}-#{blue}"
			elsif blue>red
				"BLUE #{red}-#{blue}"
			else
				"TIE #{red}-#{blue}"
			end
		else
			"-----------"
		end
	end

	def alliance(match, team)
		if match.red1_id == team.id || match.red2_id == team.id
			-1
		elsif match.blue1_id == team.id || match.blue2_id == team.id
			1
		else
			0
		end
	end

	def winningAlliance(match)
		if match.red_score > match.blue_score
			-1
		elsif match.red_score < match.blue_score
			1
		else 
			0
		end
	end

	def hasTeam(match, team)
		team.id == match.red1_id || team.id == match.red2_id || team.id == match.blue1_id || team.id == match.blue2_id
	end

	def getTeams(match)
		[match.red1, match.red2, match.blue1, match.blue2]
	end

	def partner(match, team)
		if alliance(match, team) == -1		
			if match.red1_id == team.id
				match.red2
			else 
				match.red1
			end
		elsif alliance(match, team) == 1
			if match.blue1_id == team.id
				match.blue2
			else 
				match.blue1
			end
		end
	end

	def teamWon?(match, team)
		alliance(match, team)!=0 && alliance(match,team) == winningAlliance(match)
	end

	def teamScore(match, team)
		if alliance(match, team) == -1
			match.red_score
		elsif alliance(match, team) == 1
			match.blue_score
		else
			-1
		end
	end

end

app/views/matches/_form.html.erb
<div class="row col-md-10 col-md-ofset-1">

	<h1><%= controller.action_name.capitalize %> Match </h1>
	<br>
	<%= simple_form_for([@event, @match], html:{class:'form-horizontal'}, wrapper: :horizontal_form) do |f| %>

		<% f.error_notification %>
		
		<%= f.hidden_field :event_id %>
		<%= f.hidden_field :red_score%>
		<%= f.hidden_field :blue_score %>

		<%= f.input :number, label: 'Match Number' %>
		<%= f.input :red1_id, label: 'Red 1', collection: Team.all.order(:number), label_method: :show_team %>
		<%= f.input :red2_id, label: 'Red 2', collection: Team.all.order(:number), label_method: :show_team %>
		<%= f.input :blue1_id, label: 'Blue 1', collection: Team.all.order(:number), label_method: :show_team %>
		<%= f.input :blue2_id, label: 'Blue 2', collection: Team.all.order(:number), label_method: :show_team %>
		<%= f.input :red_score %>
		<%= f.input :blue_score %>


		
		<div class="row text-right" %>
			<%= f.submit nil, class:'btn btn-primary'%>
			<%= link_to 'Cancel', :back, class:'btn btn-default' %>
		</div>
	<% end %>
</div>

app/views/matches/_match.html.erb
<tr>
	<% if can? :modify, Match %>
		<td> <a href="<%= event_match_path(match.event, match) %>"> <%= match.number %> </a></td>
	<% else  %>
		<td> <a href="<%= event_match_path(match.event, match) %>" style="color:#000000;	text-decoration: none;"> <%= match.number %> </a></td>
	<% end %>
	<td> <a href="<%= team_path(match.red1) %>" style="color:#FF0000;	text-decoration: none;"> <%= match.red1.show_team %> </a></td>
	<td> <a href="<%= team_path(match.red2) %>" style="color:#FF0000;	text-decoration: none;"> <%= match.red2.show_team %> </a></td>
	<td> <a href="<%= team_path(match.blue1) %>" style="color:#0000FF;	text-decoration: none;"> <%= match.blue1.show_team %> </a></td>
	<td> <a href="<%= team_path(match.blue2) %>" style="color:#0000FF;	text-decoration: none;"> <%= match.blue2.show_team %> </a></td>
	<td> <font color="RED"> <%= match.red_score == 0 ? '---' : match.red_score %> </font></td>
	<td> <font color="BLUE"><%= match.blue_score == 0 ? '---' : match.blue_score %> </font></td>
</tr>

app/views/matches/edit.html.erb
<%= render 'form' %>

app/views/matches/new.html.erb
<%= render 'form' %>

app/views/matches/show.html.erb
<div class="page-header">
	<h1>Match <%= @match.number %>, <%= link_to @match.event.name, @match.event %></h1>
	<h3><%= red(@match.red_score) %> - <%= blue(@match.blue_score) %></h3>
</div>

<br>
<h2><%= red("Red Alliance") %></h2>
<h4><a href="<%= team_path(@match.red1) %>" style="color:#FF0000;"> <%= @match.red1.show_team %></a></h4>
<h4><a href="<%= team_path(@match.red2) %>" style="color:#FF0000;"> <%= @match.red2.show_team %></a></h4>


<br>
<br>
<h2><%= blue("Blue Alliance") %></h2>
<h4><a href="<%= team_path(@match.blue1) %>" style="color:#0000FF;"> <%= @match.blue1.show_team %></a></h4>
<h4><a href="<%= team_path(@match.blue2) %>" style="color:#0000FF;"> <%= @match.blue2.show_team %></a></h4>

<% if can? :read, Comment %>
	<div class="text-right">
		<%= link_to 'New Comment', new_comment_path(type: 'match', match_id: @match.id), class:'btn btn-success btn-md' if can? :modify, Comment%> 
	</div>
	<h2>Comments</h2>
	<% @match.comments.each do |c| %>
	  <h4>"<%= c.body %>"</h4>
	  <div class='text-right'>
	    <h5>
	      -<%= c.author %> &nbsp;
	      <%= link_to fa_icon('pencil'), edit_comment_path(c), class:'btn btn-default btn-xs' if can? :modify, Comment%>
	      <%= link_to fa_icon('trash-o'), c, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-xs' if can? :destroy, Comment%> 
	    </h5>
	  </div>
	<% end %>
<% end %>

<br>
<br>
<div class="row text-right">
	<%= link_to fa_icon('pencil', text:'Edit Match'), edit_event_match_path(@match.event, @match), class:'btn btn-default' if can? :update, Match%> 
	<%= link_to fa_icon('trash-o', text:'Destroy Match'), event_match_path(@match.event, @match), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' if can? :destroy, Match%>
</div>	