config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams
  resources :comments
  resources :events do
    resources :matches
  end

  root 'events#index'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted credit">
    	<%= link_to "Subatomic Scouting", root_url %> powered by <%= link_to "Neutrinos (#6433)", "http://www.gofundme.com/neutrinos" %>, designed by Abhinav Venigalla.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subatomic Scouting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">

<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">

	<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  	<a class="navbar-brand" href= <%= root_url %>>
  		Subatomic Scouting
      <% if current_user != nil %>
       &nbsp; <%= show_role(current_user) %>
      <% end %>
    </a>
  </div>

	<div class="collapse navbar-collapse" id="navbar">
		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to 'FTC Teams', teams_path %></li>
			<li><%= link_to 'Florida Events', events_path %></li>

			<% if user_signed_in? %>
				<li><%= link_to 'Sign out', destroy_user_session_path, :method=>:delete %></li>
			<% else %>
				<li><%= link_to 'Sign in', new_user_session_path %></li>						
			<% end %>
		</ul>
	</div>

</div> <!-- container-fluid -->
</nav>


<div class="container">
  <% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
    </div>
  <% end %>

	<%= yield %>
	<br><br>
</div>

</div>

<%= render "/layouts/footer" %>

</body>
</html>